services:
  spring-festivall-image:
    image: spring-festivall-image
    container_name: spring-festivall-container
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: Admin123.
      MYSQL_DATABASE: proyecto
      MYSQL_USER: otton
      MYSQL_PASSWORD: 1995
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

  frontend:
    image: pi_c1_g5-frontend
    container_name: react-frontend-container
    ports:
      - "3000:3000"
    networks:
      - spring-network
    depends_on:
      - spring-festivall-image

networks:
  spring-network:

volumes:
  mysql-volume:
